#!/usr/bin/env python3
"""
Quick ICR2 .3DO viewer.

Dependencies:
    pip install pygame PyOpenGL

Usage:
    python icr2_3do_viewer.py path/to/object.3do

Controls:
    Left drag       Orbit
    Middle drag     Pan
    Mouse wheel     Zoom
    W               Toggle wireframe
    C               Toggle back-face culling
    A               Toggle axes
    R               Reset camera
    Esc             Quit

Menus:
    File > Open 3DO/3D...    Load or replace the displayed .3DO or .3D file
    File > Open sunny.pcx... Load a 256-color PCX palette for polygon colors

Scope:
    - Reads the .3DO header and body-relative record graph.
    - Reads N3 .3D text files generated by 3do23d/compatible tools.
    - Displays Flavor 1 and Flavor 2 polygons.
    - Traverses LIST, MATERIAL, FACE, BSP, distance-switch, SUPEROBJ,
      PMP and PMP2 links.
    - Does not load MIP textures yet; textured polygons are shown shaded.
    - Treats Flavor 0 targets as vertices only when referenced by polygons.
"""

from __future__ import annotations

import argparse
import math
import re
import struct
import sys
import tkinter as tk
from dataclasses import dataclass
from pathlib import Path
from tkinter import filedialog, messagebox
from typing import Iterable

try:
    import pygame
    from pygame.locals import DOUBLEBUF, OPENGL, RESIZABLE
    from OpenGL.GL import (
        GL_BACK,
        GL_BLEND,
        GL_COLOR_BUFFER_BIT,
        GL_CULL_FACE,
        GL_DEPTH_BUFFER_BIT,
        GL_DEPTH_TEST,
        GL_FILL,
        GL_FRONT_AND_BACK,
        GL_LEQUAL,
        GL_LINES,
        GL_LINE,
        GL_MODELVIEW,
        GL_NORMALIZE,
        GL_QUADS,
        GL_RGBA,
        GL_ONE_MINUS_SRC_ALPHA,
        GL_POLYGON_OFFSET_FILL,
        GL_PROJECTION,
        GL_SMOOTH,
        GL_SRC_ALPHA,
        GL_TRIANGLES,
        GL_UNSIGNED_BYTE,
        glBegin,
        glBlendFunc,
        glClear,
        glClearColor,
        glColor3f,
        glDisable,
        glEnable,
        glEnd,
        glLineWidth,
        glLoadIdentity,
        glMatrixMode,
        glNormal3f,
        glPolygonMode,
        glPolygonOffset,
        glShadeModel,
        glVertex3f,
        glViewport,
        glDepthFunc,
        glCullFace,
        glDrawPixels,
        glRasterPos2f,
        glOrtho,
        glPopMatrix,
        glPushMatrix,
    )
    from OpenGL.GLU import gluLookAt, gluPerspective
except ImportError as exc:
    raise SystemExit(
        "Missing dependency. Install with:\n"
        "    pip install pygame PyOpenGL\n"
    ) from exc


FLAVOR_MASK = 0x80000000


class FormatError(ValueError):
    pass


@dataclass(frozen=True)
class Header:
    body_size: int
    root_offset: int
    mip_names: tuple[str, ...]
    pmp_names: tuple[str, ...]
    object_names: tuple[str, ...]
    body_file_offset: int


@dataclass(frozen=True)
class Vertex:
    x: float
    y: float
    z: float
    u: int | None = None
    v: int | None = None


@dataclass
class Polygon:
    vertices: list[Vertex]
    color_index: int
    textured: bool


@dataclass
class Model:
    polygons: list[Polygon]
    center: tuple[float, float, float]
    radius: float
    header: Header


@dataclass(frozen=True)
class Palette:
    colors: tuple[tuple[float, float, float], ...]
    filename: Path


class Reader:
    def __init__(self, data: bytes):
        self.data = data

    def _check(self, offset: int, size: int) -> None:
        if offset < 0 or offset + size > len(self.data):
            raise FormatError(
                f"Read outside buffer: offset={offset}, size={size}, "
                f"buffer={len(self.data)}"
            )

    def i16(self, offset: int) -> int:
        self._check(offset, 2)
        return struct.unpack_from("<h", self.data, offset)[0]

    def u16(self, offset: int) -> int:
        self._check(offset, 2)
        return struct.unpack_from("<H", self.data, offset)[0]

    def i32(self, offset: int) -> int:
        self._check(offset, 4)
        return struct.unpack_from("<i", self.data, offset)[0]

    def u32(self, offset: int) -> int:
        self._check(offset, 4)
        return struct.unpack_from("<I", self.data, offset)[0]

    def i64(self, offset: int) -> int:
        self._check(offset, 8)
        return struct.unpack_from("<q", self.data, offset)[0]

    def bytes(self, offset: int, size: int) -> bytes:
        self._check(offset, size)
        return self.data[offset : offset + size]


class ThreeDOParser:
    def __init__(self, filename: Path):
        self.filename = filename
        self.file_data = filename.read_bytes()
        self.file = Reader(self.file_data)
        self.header = self._read_header()
        body_end = self.header.body_file_offset + self.header.body_size
        if body_end > len(self.file_data):
            raise FormatError(
                f"Header declares a {self.header.body_size}-byte body, "
                f"but only {len(self.file_data) - self.header.body_file_offset} "
                "bytes remain."
            )
        self.body_data = self.file_data[self.header.body_file_offset:body_end]
        self.body = Reader(self.body_data)

        self.polygons: list[Polygon] = []
        self.visited_records: set[int] = set()
        self.vertex_cache: dict[tuple[int, bool], Vertex] = {}
        self.warnings: list[str] = []

    def _read_header(self) -> Header:
        if len(self.file_data) < 20:
            raise FormatError("File is shorter than the 20-byte header.")

        body_size = self.file.i32(0)
        root_offset = self.file.i32(4)
        mip_count = self.file.i32(8)
        pmp_count = self.file.i32(12)
        object_count = self.file.i32(16)

        for name, value in (
            ("body_size", body_size),
            ("mip_count", mip_count),
            ("pmp_count", pmp_count),
            ("object_count", object_count),
        ):
            if value < 0:
                raise FormatError(f"Negative {name}: {value}")

        total_names = mip_count + pmp_count + object_count
        header_size = 20 + total_names * 8
        if header_size > len(self.file_data):
            raise FormatError("Resource-name tables extend beyond the file.")

        names = []
        pos = 20
        for _ in range(total_names):
            raw = self.file.bytes(pos, 8)
            names.append(raw.split(b"\0", 1)[0].decode("ascii", errors="replace"))
            pos += 8

        mip_names = tuple(names[:mip_count])
        pmp_names = tuple(names[mip_count:mip_count + pmp_count])
        object_names = tuple(names[mip_count + pmp_count:])

        if body_size and not (0 <= root_offset < body_size):
            raise FormatError(
                f"Root offset {root_offset} is outside body size {body_size}."
            )

        return Header(
            body_size=body_size,
            root_offset=root_offset,
            mip_names=mip_names,
            pmp_names=pmp_names,
            object_names=object_names,
            body_file_offset=header_size,
        )

    def _valid_offset(self, offset: int, minimum_size: int = 4) -> bool:
        return 0 <= offset <= len(self.body_data) - minimum_size

    def _read_vertex(self, offset: int, textured: bool) -> Vertex:
        key = (offset, textured)
        if key in self.vertex_cache:
            return self.vertex_cache[key]

        size = 20 if textured else 16
        if not self._valid_offset(offset, size):
            raise FormatError(f"Invalid vertex offset {offset}.")

        # Flavor 0 is ambiguous, but polygon context identifies this as a vertex.
        x = self.body.i32(offset + 4)
        y = self.body.i32(offset + 8)
        z = self.body.i32(offset + 12)
        if textured:
            vertex = Vertex(x, y, z, self.body.u16(offset + 16), self.body.u16(offset + 18))
        else:
            vertex = Vertex(x, y, z)

        self.vertex_cache[key] = vertex
        return vertex

    def _queue_pointer(self, queue: list[int], pointer: int, source: str) -> None:
        if self._valid_offset(pointer):
            queue.append(pointer)
        else:
            self.warnings.append(f"{source}: ignored invalid pointer {pointer}")

    def parse(self) -> Model:
        queue = [self.header.root_offset]

        while queue:
            offset = queue.pop()
            if offset in self.visited_records:
                continue
            if not self._valid_offset(offset):
                self.warnings.append(f"Ignored invalid record offset {offset}")
                continue

            self.visited_records.add(offset)
            raw_flavor = self.body.u32(offset)
            flavor = 0 if raw_flavor == 0 else raw_flavor & 0xFF

            try:
                if flavor == 0:
                    # NIL or vertex. Vertices are decoded only from polygon context.
                    continue

                if flavor == 1:
                    color = self.body.i32(offset + 4)
                    count = self.body.i32(offset + 8) + 1
                    if count < 0 or count > 100000:
                        raise FormatError(f"Invalid POLY vertex count {count}")
                    pointers = [self.body.i32(offset + 12 + i * 4) for i in range(count)]
                    verts = [self._read_vertex(p, False) for p in pointers]
                    if len(verts) >= 3:
                        self.polygons.append(Polygon(verts, color, False))
                    continue

                if flavor == 2:
                    color = self.body.i32(offset + 8)
                    count = self.body.i32(offset + 12) + 1
                    if count < 0 or count > 100000:
                        raise FormatError(f"Invalid textured POLY vertex count {count}")
                    pointers = [self.body.i32(offset + 16 + i * 4) for i in range(count)]
                    verts = [self._read_vertex(p, True) for p in pointers]
                    if len(verts) >= 3:
                        self.polygons.append(Polygon(verts, color, True))
                    continue

                if flavor in (3, 18):  # PMP / PMP2
                    self._queue_pointer(queue, self.body.i32(offset + 4), f"Flavor {flavor}")
                    continue

                if flavor == 4:  # MATERIAL
                    self._queue_pointer(queue, self.body.i32(offset + 12), "MATERIAL")
                    continue

                if flavor == 5:  # FACE
                    self._queue_pointer(queue, self.body.i32(offset + 24), "FACE")
                    continue

                if flavor == 6:  # FACE2
                    self._queue_pointer(queue, self.body.i32(offset + 24), "FACE2")
                    self._queue_pointer(queue, self.body.i32(offset + 28), "FACE2")
                    continue

                if flavor in (7, 8):  # BSPF / BSPA
                    for p in (24, 28, 32):
                        self._queue_pointer(queue, self.body.i32(offset + p), f"BSP flavor {flavor}")
                    continue

                if flavor == 9:  # BSP2
                    for p in (24, 28, 32, 36):
                        self._queue_pointer(queue, self.body.i32(offset + p), "BSP2")
                    continue

                if flavor == 10:  # BSPN
                    for p in (24, 28):
                        self._queue_pointer(queue, self.body.i32(offset + p), "BSPN")
                    continue

                if flavor == 11:  # LIST
                    count = self.body.i32(offset + 4)
                    if count < 0 or count > 100000:
                        raise FormatError(f"Invalid LIST count {count}")
                    for i in range(count):
                        self._queue_pointer(
                            queue,
                            self.body.i32(offset + 8 + i * 4),
                            "LIST",
                        )
                    continue

                if flavor == 12:  # DYNO: no body child offsets
                    continue

                if flavor == 13:  # Distance switch
                    for p in (12, 20, 28, 36):
                        self._queue_pointer(queue, self.body.i32(offset + p), "Distance switch")
                    continue

                if flavor == 14:  # RECOLOR: no body child offsets
                    continue

                if flavor == 15:  # DYNAMIC: external object, not loaded here
                    continue

                if flavor == 16:  # SUPEROBJ
                    self._queue_pointer(queue, self.body.i32(offset + 4), "SUPEROBJ previous")
                    count = self.body.i32(offset + 8)
                    if count < 0 or count > 100000:
                        raise FormatError(f"Invalid SUPEROBJ count {count}")
                    for i in range(count):
                        self._queue_pointer(
                            queue,
                            self.body.i32(offset + 12 + i * 4),
                            "SUPEROBJ",
                        )
                    continue

                if flavor == 17:  # DATA
                    continue

                self.warnings.append(
                    f"Unknown flavor 0x{raw_flavor:08X} at body offset {offset}"
                )

            except (FormatError, struct.error) as exc:
                self.warnings.append(f"Record at body offset {offset}: {exc}")

        if not self.polygons:
            raise FormatError(
                "No reachable Flavor 1 or Flavor 2 polygons were found."
            )

        all_vertices = [v for p in self.polygons for v in p.vertices]
        min_x = min(v.x for v in all_vertices)
        min_y = min(v.y for v in all_vertices)
        min_z = min(v.z for v in all_vertices)
        max_x = max(v.x for v in all_vertices)
        max_y = max(v.y for v in all_vertices)
        max_z = max(v.z for v in all_vertices)

        center = (
            (min_x + max_x) * 0.5,
            (min_y + max_y) * 0.5,
            (min_z + max_z) * 0.5,
        )
        radius = max(
            math.dist((v.x, v.y, v.z), center) for v in all_vertices
        )
        if radius <= 0:
            radius = 1.0

        return Model(self.polygons, center, radius, self.header)


class ThreeDTextParser:
    """Parse displayable geometry from an N3 .3D text file."""

    LABEL_RE = re.compile(r"^\s*_([A-Za-z0-9]+)\s*:\s*(.*?)\s*;?\s*$", re.DOTALL)
    VERTEX_RE = re.compile(
        r"^\[\s*<\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*>\s*"
        r"(?:,\s*T\s*=\s*<\s*(-?\d+)\s*,\s*(-?\d+)\s*>\s*)?\]$",
        re.IGNORECASE,
    )
    POLY_RE = re.compile(
        r"^POLY\s*(\[T\])?\s*<\s*(-?\d+)\s*>\s*\{([^}]*)\}",
        re.IGNORECASE | re.DOTALL,
    )
    POINTER_RE = re.compile(r"_([A-Za-z0-9]+)")

    def __init__(self, filename: Path):
        self.filename = filename
        self.text = filename.read_text(encoding="utf-8", errors="replace")
        self.vertices: dict[str, Vertex] = {}
        self.polygons: list[Polygon] = []
        self.warnings: list[str] = []

    def _statements(self) -> Iterable[tuple[str, str]]:
        for statement in self.text.split(";"):
            statement = statement.strip()
            if not statement or statement.upper().startswith("3D VERSION"):
                continue
            match = self.LABEL_RE.match(statement)
            if match is None:
                continue
            yield match.group(1), match.group(2).strip()

    def parse(self) -> Model:
        statements = list(self._statements())

        for label, command in statements:
            match = self.VERTEX_RE.match(command)
            if match is None:
                continue
            x, y, z, u, v = match.groups()
            self.vertices[label] = Vertex(
                float(x),
                float(y),
                float(z),
                int(u) if u is not None else None,
                int(v) if v is not None else None,
            )

        for label, command in statements:
            match = self.POLY_RE.match(command)
            if match is None:
                continue
            textured = bool(match.group(1))
            color = int(match.group(2))
            vertex_labels = self.POINTER_RE.findall(match.group(3))
            verts = []
            missing = []
            for vertex_label in vertex_labels:
                vertex = self.vertices.get(vertex_label)
                if vertex is None:
                    missing.append(vertex_label)
                else:
                    verts.append(vertex)
            if missing:
                self.warnings.append(
                    f"POLY _{label}: missing vertices "
                    + ", ".join(f"_{item}" for item in missing)
                )
            if len(verts) >= 3:
                self.polygons.append(Polygon(verts, color, textured))

        if not self.polygons:
            raise FormatError("No POLY statements with at least three vertices were found.")

        all_vertices = [v for p in self.polygons for v in p.vertices]
        min_x = min(v.x for v in all_vertices)
        min_y = min(v.y for v in all_vertices)
        min_z = min(v.z for v in all_vertices)
        max_x = max(v.x for v in all_vertices)
        max_y = max(v.y for v in all_vertices)
        max_z = max(v.z for v in all_vertices)
        center = (
            (min_x + max_x) * 0.5,
            (min_y + max_y) * 0.5,
            (min_z + max_z) * 0.5,
        )
        radius = max(math.dist((v.x, v.y, v.z), center) for v in all_vertices)
        if radius <= 0:
            radius = 1.0

        header = Header(
            body_size=len(self.text),
            root_offset=0,
            mip_names=(),
            pmp_names=(),
            object_names=(),
            body_file_offset=0,
        )
        return Model(self.polygons, center, radius, header)


def load_model_file(filename: Path) -> tuple[Model, list[str], int | None]:
    if filename.suffix.lower() == ".3d":
        parser = ThreeDTextParser(filename)
        model = parser.parse()
        return model, parser.warnings, None

    parser = ThreeDOParser(filename)
    model = parser.parse()
    return model, parser.warnings, len(parser.visited_records)


def normalize(v: tuple[float, float, float]) -> tuple[float, float, float]:
    length = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    if length <= 1e-12:
        return (0.0, 0.0, 1.0)
    return (v[0] / length, v[1] / length, v[2] / length)


def polygon_normal(vertices: list[Vertex]) -> tuple[float, float, float]:
    # Newell's method handles polygons with more than three vertices.
    nx = ny = nz = 0.0
    for current, nxt in zip(vertices, vertices[1:] + vertices[:1]):
        nx += (current.y - nxt.y) * (current.z + nxt.z)
        ny += (current.z - nxt.z) * (current.x + nxt.x)
        nz += (current.x - nxt.x) * (current.y + nxt.y)
    return normalize((nx, ny, nz))


def load_pcx_palette(filename: Path) -> Palette:
    """Load the 256-color VGA palette stored at the end of an 8-bit PCX file."""
    data = filename.read_bytes()
    if len(data) < 769:
        raise FormatError("PCX file is too short to contain a 256-color palette.")
    if data[-769] != 0x0C:
        raise FormatError("PCX file does not contain a trailing 256-color VGA palette.")

    palette_data = data[-768:]
    colors = tuple(
        (
            palette_data[i] / 255.0,
            palette_data[i + 1] / 255.0,
            palette_data[i + 2] / 255.0,
        )
        for i in range(0, 768, 3)
    )
    return Palette(colors=colors, filename=filename)


def color_from_index(index: int, textured: bool, palette: Palette | None = None) -> tuple[float, float, float]:
    if palette is not None:
        r, g, b = palette.colors[index & 0xFF]
    else:
        # Placeholder visualization palette. It intentionally does not claim to
        # reproduce the game's palette.
        seed = index & 0xFFFFFFFF
        r = 0.35 + ((seed * 97) & 0xFF) / 510.0
        g = 0.35 + ((seed * 57 + 83) & 0xFF) / 510.0
        b = 0.35 + ((seed * 23 + 161) & 0xFF) / 510.0
    if textured:
        # Slightly neutralize textured polygons until MIP loading is added.
        average = (r + g + b) / 3.0
        r = r * 0.6 + average * 0.4
        g = g * 0.6 + average * 0.4
        b = b * 0.6 + average * 0.4
    return (min(r, 1.0), min(g, 1.0), min(b, 1.0))


class Viewer:
    MENU_HEIGHT = 28
    MENU_WIDTH = 72

    def __init__(self, model: Model | None = None, filename: Path | None = None):
        self.model = model
        self.filename = filename
        self.palette: Palette | None = None
        self.menu_open = False
        self._tk_root: tk.Tk | None = None

        self.width = 1100
        self.height = 750
        self.yaw = 40.0
        self.pitch = 25.0
        self.distance = (model.radius * 3.0) if model is not None else 1000.0
        self.pan = [0.0, 0.0, 0.0]

        self.wireframe = False
        self.culling = False
        self.show_axes = True

        self.left_drag = False
        self.middle_drag = False
        self.last_mouse = (0, 0)

    def reset_camera(self) -> None:
        self.yaw = 40.0
        self.pitch = 25.0
        self.distance = (self.model.radius * 3.0) if self.model is not None else 1000.0
        self.pan[:] = [0.0, 0.0, 0.0]

    def _caption(self) -> str:
        if self.model is None or self.filename is None:
            return "ICR2 3DO Viewer — no .3DO/.3D loaded"
        palette = f" — palette: {self.palette.filename.name}" if self.palette else ""
        return (
            f"ICR2 3DO Viewer — {self.filename.name} — "
            f"{len(self.model.polygons)} polygons{palette}"
        )

    def _load_model(self, filename: Path) -> None:
        self.model, warnings, reachable_records = load_model_file(filename)
        self.filename = filename
        self.reset_camera()
        pygame.display.set_caption(self._caption())
        print(f"Loaded: {filename}")
        if reachable_records is not None:
            print(f"Reachable records: {reachable_records:,}")
        print(f"Polygons: {len(self.model.polygons):,}")
        if warnings:
            print(f"Warnings: {len(warnings)}")
            for warning in warnings[:20]:
                print(f"  - {warning}")

    def _tk(self) -> tk.Tk:
        if self._tk_root is None:
            self._tk_root = tk.Tk()
            self._tk_root.withdraw()
        return self._tk_root

    def _open_3do_dialog(self) -> None:
        path = filedialog.askopenfilename(
            parent=self._tk(),
            title="Open ICR2 3DO or N3 3D file",
            filetypes=(("3DO/3D files", "*.3do *.3DO *.3d *.3D"), ("All files", "*.*")),
        )
        if not path:
            return
        try:
            self._load_model(Path(path))
        except (OSError, FormatError) as exc:
            messagebox.showerror("Could not load model", str(exc), parent=self._tk())

    def _open_palette_dialog(self) -> None:
        path = filedialog.askopenfilename(
            parent=self._tk(),
            title="Open sunny.pcx palette",
            filetypes=(("PCX palette files", "*.pcx *.PCX"), ("All files", "*.*")),
        )
        if not path:
            return
        try:
            self.palette = load_pcx_palette(Path(path))
            pygame.display.set_caption(self._caption())
            print(f"Loaded palette: {path}")
        except (OSError, FormatError) as exc:
            messagebox.showerror("Could not load PCX palette", str(exc), parent=self._tk())

    def _camera_position(self) -> tuple[float, float, float]:
        center = self.model.center if self.model is not None else (0.0, 0.0, 0.0)
        yaw = math.radians(self.yaw)
        pitch = math.radians(self.pitch)
        horizontal = self.distance * math.cos(pitch)
        return (
            center[0] + self.pan[0] + horizontal * math.cos(yaw),
            center[1] + self.pan[1] + horizontal * math.sin(yaw),
            center[2] + self.pan[2] + self.distance * math.sin(pitch),
        )

    def _target(self) -> tuple[float, float, float]:
        center = self.model.center if self.model is not None else (0.0, 0.0, 0.0)
        return (
            center[0] + self.pan[0],
            center[1] + self.pan[1],
            center[2] + self.pan[2],
        )

    def _set_projection(self) -> None:
        glViewport(0, 0, max(self.width, 1), max(self.height, 1))
        glMatrixMode(GL_PROJECTION)
        glLoadIdentity()
        radius = self.model.radius if self.model is not None else 1000.0
        near = max(radius * 0.001, 0.01)
        far = max(radius * 100.0, near + 1.0)
        gluPerspective(45.0, self.width / max(self.height, 1), near, far)
        glMatrixMode(GL_MODELVIEW)

    def _draw_axes(self) -> None:
        if not self.show_axes or self.model is None:
            return
        length = self.model.radius * 0.75
        cx, cy, cz = self.model.center
        glLineWidth(2.0)
        glBegin(GL_LINES)
        glColor3f(1.0, 0.15, 0.15)
        glVertex3f(cx, cy, cz)
        glVertex3f(cx + length, cy, cz)
        glColor3f(0.15, 1.0, 0.15)
        glVertex3f(cx, cy, cz)
        glVertex3f(cx, cy + length, cz)
        glColor3f(0.15, 0.35, 1.0)
        glVertex3f(cx, cy, cz)
        glVertex3f(cx, cy, cz + length)
        glEnd()
        glLineWidth(1.0)

    def _draw_model(self) -> None:
        if self.model is None:
            return

        glPolygonMode(GL_FRONT_AND_BACK, GL_LINE if self.wireframe else GL_FILL)

        for polygon in self.model.polygons:
            if len(polygon.vertices) < 3:
                continue

            normal = polygon_normal(polygon.vertices)
            color = color_from_index(polygon.color_index, polygon.textured, self.palette)
            glColor3f(*color)
            glNormal3f(*normal)

            # Triangle fan. Suitable for the mostly convex polygons used by
            # ICR2 assets; concave polygons may require proper triangulation.
            first = polygon.vertices[0]
            glBegin(GL_TRIANGLES)
            for i in range(1, len(polygon.vertices) - 1):
                for vertex in (first, polygon.vertices[i], polygon.vertices[i + 1]):
                    glVertex3f(vertex.x, vertex.y, vertex.z)
            glEnd()

        glPolygonMode(GL_FRONT_AND_BACK, GL_FILL)

    def _draw_text(self, font: pygame.font.Font, text: str, x: int, y: int) -> None:
        surface = font.render(text, True, (235, 235, 235, 255))
        data = pygame.image.tostring(surface, "RGBA", True)
        glRasterPos2f(x, self.height - y - surface.get_height())
        glDrawPixels(surface.get_width(), surface.get_height(), GL_RGBA, GL_UNSIGNED_BYTE, data)

    def _draw_rect(self, x: int, y: int, width: int, height: int, color: tuple[float, float, float]) -> None:
        left = x
        right = x + width
        top = self.height - y
        bottom = self.height - y - height
        glColor3f(*color)
        glBegin(GL_QUADS)
        glVertex3f(left, bottom, 0.0)
        glVertex3f(right, bottom, 0.0)
        glVertex3f(right, top, 0.0)
        glVertex3f(left, top, 0.0)
        glEnd()

    def _draw_menu(self, font: pygame.font.Font) -> None:
        glMatrixMode(GL_PROJECTION)
        glPushMatrix()
        glLoadIdentity()
        glOrtho(0, self.width, 0, self.height, -1, 1)
        glMatrixMode(GL_MODELVIEW)
        glPushMatrix()
        glLoadIdentity()
        glDisable(GL_DEPTH_TEST)

        self._draw_rect(0, 0, self.width, self.MENU_HEIGHT, (0.12, 0.13, 0.15))
        self._draw_rect(0, 0, self.MENU_WIDTH, self.MENU_HEIGHT, (0.18, 0.19, 0.22) if self.menu_open else (0.12, 0.13, 0.15))
        self._draw_text(font, "File", 16, 7)
        if self.menu_open:
            self._draw_rect(0, self.MENU_HEIGHT, 210, 64, (0.16, 0.17, 0.19))
            self._draw_text(font, "Open 3DO/3D...", 12, self.MENU_HEIGHT + 8)
            self._draw_text(font, "Open sunny.pcx...", 12, self.MENU_HEIGHT + 38)

        glEnable(GL_DEPTH_TEST)
        glMatrixMode(GL_MODELVIEW)
        glPopMatrix()
        glMatrixMode(GL_PROJECTION)
        glPopMatrix()
        glMatrixMode(GL_MODELVIEW)

    def _handle_menu_click(self, position: tuple[int, int]) -> bool:
        x, y = position
        if y < self.MENU_HEIGHT and x < self.MENU_WIDTH:
            self.menu_open = not self.menu_open
            return True
        if not self.menu_open:
            return False
        self.menu_open = False
        if 0 <= x <= 210 and self.MENU_HEIGHT <= y < self.MENU_HEIGHT + 32:
            self._open_3do_dialog()
            return True
        if 0 <= x <= 210 and self.MENU_HEIGHT + 32 <= y < self.MENU_HEIGHT + 64:
            self._open_palette_dialog()
            return True
        return True

    def _pan_camera(self, dx: float, dy: float) -> None:
        yaw = math.radians(self.yaw)
        right = (-math.sin(yaw), math.cos(yaw), 0.0)
        up = (0.0, 0.0, 1.0)
        scale = self.distance * 0.0015
        for i in range(3):
            self.pan[i] += right[i] * (-dx * scale) + up[i] * (dy * scale)

    def run(self) -> None:
        pygame.init()
        pygame.display.gl_set_attribute(pygame.GL_DEPTH_SIZE, 24)
        pygame.display.gl_set_attribute(pygame.GL_DOUBLEBUFFER, 1)
        pygame.display.set_mode(
            (self.width, self.height),
            DOUBLEBUF | OPENGL | RESIZABLE,
        )
        pygame.display.set_caption(self._caption())
        font = pygame.font.Font(None, 22)

        glClearColor(0.08, 0.09, 0.11, 1.0)
        glEnable(GL_DEPTH_TEST)
        glDepthFunc(GL_LEQUAL)
        glEnable(GL_NORMALIZE)
        glShadeModel(GL_SMOOTH)
        glEnable(GL_BLEND)
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
        glCullFace(GL_BACK)

        clock = pygame.time.Clock()
        running = True

        while running:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False

                elif event.type == pygame.VIDEORESIZE:
                    self.width = max(event.w, 1)
                    self.height = max(event.h, 1)

                elif event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_ESCAPE:
                        running = False
                    elif event.key == pygame.K_w:
                        self.wireframe = not self.wireframe
                    elif event.key == pygame.K_c:
                        self.culling = not self.culling
                    elif event.key == pygame.K_a:
                        self.show_axes = not self.show_axes
                    elif event.key == pygame.K_r:
                        self.reset_camera()

                elif event.type == pygame.MOUSEBUTTONDOWN:
                    if event.button == 1 and self._handle_menu_click(event.pos):
                        self.last_mouse = event.pos
                        continue
                    if event.button == 1:
                        self.left_drag = True
                    elif event.button == 2:
                        self.middle_drag = True
                    elif event.button == 4:
                        self.distance = max(
                            (self.model.radius * 0.02) if self.model is not None else 20.0,
                            self.distance * 0.88,
                        )
                    elif event.button == 5:
                        self.distance *= 1.14
                    self.last_mouse = event.pos

                elif event.type == pygame.MOUSEBUTTONUP:
                    if event.button == 1:
                        self.left_drag = False
                    elif event.button == 2:
                        self.middle_drag = False

                elif event.type == pygame.MOUSEWHEEL:
                    if event.y > 0:
                        self.distance = max(
                            (self.model.radius * 0.02) if self.model is not None else 20.0,
                            self.distance * (0.88 ** event.y),
                        )
                    elif event.y < 0:
                        self.distance *= 1.14 ** (-event.y)

                elif event.type == pygame.MOUSEMOTION:
                    dx = event.pos[0] - self.last_mouse[0]
                    dy = event.pos[1] - self.last_mouse[1]
                    self.last_mouse = event.pos

                    if self.left_drag:
                        self.yaw += dx * 0.35
                        self.pitch = max(-89.0, min(89.0, self.pitch - dy * 0.35))
                    elif self.middle_drag:
                        self._pan_camera(dx, dy)

            self._set_projection()
            glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
            glLoadIdentity()

            camera = self._camera_position()
            target = self._target()
            gluLookAt(
                camera[0], camera[1], camera[2],
                target[0], target[1], target[2],
                0.0, 0.0, 1.0,
            )

            if self.culling:
                glEnable(GL_CULL_FACE)
            else:
                glDisable(GL_CULL_FACE)

            self._draw_model()
            glDisable(GL_CULL_FACE)
            self._draw_axes()
            self._draw_menu(font)

            pygame.display.flip()
            clock.tick(120)

        pygame.quit()


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Quick OpenGL viewer for ICR2 .3DO and N3 .3D files.")
    parser.add_argument("file", type=Path, nargs="?", help="Path to an ICR2 .3DO or N3 .3D file")
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    model = None
    if args.file is not None:
        if not args.file.is_file():
            print(f"File not found: {args.file}", file=sys.stderr)
            return 2

        try:
            model, warnings, reachable_records = load_model_file(args.file)
        except (OSError, FormatError) as exc:
            print(f"Could not load {args.file}: {exc}", file=sys.stderr)
            return 1

        print(f"Loaded: {args.file}")
        print(f"Body size: {model.header.body_size:,} bytes")
        if reachable_records is not None:
            print(f"Reachable records: {reachable_records:,}")
        print(f"Polygons: {len(model.polygons):,}")
        print(f"MIP resources: {len(model.header.mip_names)}")
        print(f"PMP resources: {len(model.header.pmp_names)}")
        print(f"External 3DO resources: {len(model.header.object_names)}")
        if warnings:
            print(f"Warnings: {len(warnings)}")
            for warning in warnings[:20]:
                print(f"  - {warning}")
            if len(warnings) > 20:
                print(f"  ... {len(warnings) - 20} more")

    Viewer(model, args.file).run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
